import { Injectable } from '@angular/core';
// import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ProdService {

  vehicles: any = [
    {
      id: 1,
      vehicle_name: 'Bikes',
      vehicle_id: 'bikes',
      vehicleImg: 'assets/bike red.jpg',
      desc1: 'A motorcycle (motorbike, bike, or trike (if three-wheeled)) is a two or three-wheeled motor vehicle steered by a handlebar from a saddle-style seat.',
      desc2: 'Globally, motorcycles are comparably popular to cars as a method of transport. In 2021, approximately 58.6 million new motorcycles were sold around the world,[6] fewer than the 66.7 million cars sold over the same period.',
      prod_item: [
        {
          item_id: 'Bajaj Pulsar',
          desc: " powered by a 164.82 cc air-cooled engine which produces 16 PS @ 8750 rpm of power.",
          company: 'Bajaj',
          model_name: 'Bajaj Pulsar N160',
          price: '₹ 1,22,974',
          color: 'Red, Black, Blue',
          color1: 'Black',
          color2: 'Red',
          color3: 'Blue',
          itemImg: 'assets/pulsar.jpg',
          itemImg1: 'assets/pulsar.jpg',
          itemImg2: 'assets/pulsar2.jpg',
          itemImg3: 'assets/pulsar3.jpg',
          engine_capacity: '164.82 cc',
          mileage: '51.6 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '152 kg',
          fuel_tank_capacity: '14 litres',
          seat_height: '795 mm',
          rating: '4.6'
        },
        {
          item_id: 'Suzuki Gixxer SF',
          desc: "powered by a 155 cc air-cooled engine which produces 13.6 PS @ 8000 rpm of power.",
          company: 'Suzuki',
          model_name: 'Suzuki Gixxer SF',
          price: '₹ 1,35,740',
          color: 'Blue, Black, Orange',
          color1: 'Black',
          color2: 'Orange',
          color3: 'Blue',
          itemImg: 'assets/gixxer.jpg',
          itemImg1: 'assets/gixxer1.jpg',
          itemImg2: 'assets/gixxer2.jpg',
          itemImg3: 'assets/gixxer3.jpg',
          engine_capacity: '155 cc',
          mileage: '45 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '148 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '795 mm',
          rating: '4.5'
        },
        {
          item_id: 'BMW R Nine T Scrambler',
          desc: "powered by 1170cc BS6 engine which develops a power of 107.28 bhp and a torque of 116 Nm.",
          company: 'BMW',
          model_name: 'BMW R Nine T Scrambler',
          price: '₹ 20,12,775',
          color: 'Red, Steel, Brass',
          color1: 'Red',
          color2: 'Steel',
          color3: 'Brass',
          itemImg: 'assets/scrambler.jpg',
          itemImg1: 'assets/scrambler1.jpg',
          itemImg2: 'assets/scrambler2.jpg',
          itemImg3: 'assets/scrambler3.jpg',
          engine_capacity: '1,170 cc',
          mileage: '19.6 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '223 kg',
          fuel_tank_capacity: '17 litres',
          seat_height: '820 mm',
          rating: '5'
        },
        {
          item_id: 'Honda Unicorn',
          desc: "powered by 162.7cc BS6 engine which develops a power of 12.73 bhp and a torque of 14 Nm.",
          company: 'Honda',
          model_name: 'Honda Unicorn',
          price: '₹ 1,04,985',
          color: 'Black, Red, Steel',
          color1: 'Black',
          color2: 'Red',
          color3: 'Steel',
          itemImg: 'assets/unicorn.jpg',
          itemImg1: 'assets/unicorn1.jpg',
          itemImg2: 'assets/unicorn2.jpg',
          itemImg3: 'assets/unicorn3.jpg',
          engine_capacity: '162.7 cc',
          mileage: '50 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '140 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '798 mm',
          rating: '4.2'
        },
        {
          item_id: 'Ducati Scrambler Icon',
          desc: "powered by 803cc BS6 engine which develops a power of 71.87 bhp and a torque of 66.2 Nm.",
          company: 'Ducati',
          model_name: 'Ducati Scrambler Icon',
          price: '₹ 10,94,957',
          color: 'Yellow, Orenge, Black',
          color1: 'Yellow',
          color2: 'Orenge',
          color3: 'Black',
          itemImg: 'assets/scramblericon.jpg',
          itemImg1: 'assets/scramblericon1.jpg',
          itemImg2: 'assets/scramblericon2.jpg',
          itemImg3: 'assets/scramblericon3.jpg',
          engine_capacity: '803 cc',
          mileage: '19 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '189 kg',
          fuel_tank_capacity: '13.5 litres',
          seat_height: '798 mm',
          rating: '4.8'
        },
        {
          item_id: 'TVS Apache',
          desc: "powered by a 159.7 cc air-cooled engine which produces 16.04 PS @ 8750 rpm of power.",
          company: 'TVS',
          model_name: 'TVS Apache RTR 160 4V',
          price: '₹ 1,24,339',
          color: 'White, Black, Red',
          color1: 'White',
          color2: 'Red',
          color3: 'Black',
          itemImg: 'assets/apache.jpg',
          itemImg1: 'assets/apache.jpg',
          itemImg2: 'assets/apache2.jpg',
          itemImg3: 'assets/apache3.jpg',
          engine_capacity: '159.7 cc',
          mileage: '41.4 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '144 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '800 mm',
          rating: '4.4'
        },
        {
          item_id: 'Yamaha FZ S',
          desc: "powered by 149cc BS6 engine which develops a power of 12.2 bhp and a torque of 13.3 Nm.",
          company: 'Yamaha',
          model_name: 'Yamaha FZ S FI',
          price: '₹ 1,47,461',
          color: 'Red, Blue, Black',
          color1: 'Blue',
          color2: 'Red',
          color3: 'Black',
          itemImg: 'assets/fzs.jpg',
          itemImg1: 'assets/fzs.jpg',
          itemImg2: 'assets/fzs1.jpg',
          itemImg3: 'assets/fzs2.jpg',
          engine_capacity: '149 cc',
          mileage: '45 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '135 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '790 mm',
          rating: '4.2'
        },
        {
          item_id: 'Royal Enfield Bullet',
          desc: "powered by a 349.34 cc air-cooled engine which produces 20.21 PS @ 6100 rpm of power.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Bullet 350',
          price: '₹ 1,50,894',
          color: 'Steel, Black, Maroon',
          color1: 'Steel',
          color2: 'Maroon',
          color3: 'Black',
          itemImg: 'assets/bullet.jpg',
          itemImg1: 'assets/bullet.jpg',
          itemImg2: 'assets/bullet2.jpg',
          itemImg3: 'assets/bullet3.jpg',
          engine_capacity: '346 cc',
          mileage: '38 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '191 kg',
          fuel_tank_capacity: '13.5 litres',
          seat_height: '798 mm',
          rating: '4.5'
        },
        {
          item_id: 'Harley-Davidson Fat Boy',
          desc: "powered by 1868cc BS6 engine which develops a power of 92.5 bhp and a torque of 155 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Fat Boy',
          price: '₹ 28,45,861',
          color: 'Maroon, Blue, Black',
          color1: 'Blue',
          color2: 'Maroon',
          color3: 'Black',
          itemImg: 'assets/fatboy.jpg',
          itemImg1: 'assets/fatboy.jpg',
          itemImg2: 'assets/fatboy1.jpg',
          itemImg3: 'assets/fatboy2.jpg',
          engine_capacity: '1,868 cc',
          mileage: '18 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '317 kg',
          fuel_tank_capacity: '18.9 litres',
          seat_height: '675 mm',
          rating: '4.5'
        },
        {
          item_id: 'Hero Splendor',
          desc: "powered by a 97.2 cc air-cooled engine which produces 8.02 PS @ 8000 rpm of power.",
          company: 'Hero',
          model_name: 'Hero Splendor Plus',
          price: '₹ 72,471',
          color: 'Black, White, Golden',
          color1: 'White',
          color2: 'Golden',
          color3: 'Black',
          itemImg: 'assets/splendor.jpg',
          itemImg1: 'assets/splendor.jpg',
          itemImg2: 'assets/splendor2.jpg',
          itemImg3: 'assets/splendor3.jpg',
          engine_capacity: '	97.2 cc',
          mileage: '60 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '112 kg',
          fuel_tank_capacity: '9.8 litres',
          seat_height: '785 mm',
          rating: '4.5'
        },
        {
          item_id: 'Yamaha R15',
          desc: "powered by a 155 ccbs6 engine which develops a power of 18.4 PS and a torque of 14.2 Nm.",
          company: 'Yamaha',
          model_name: 'Yamaha R15 V4',
          price: '₹ 2,21,027',
          color: 'Red, Blue, Black',
          color1: 'Red',
          color2: 'Blue',
          color3: 'Black',
          itemImg: 'assets/r15.jpg',
          itemImg1: 'assets/r15.jpg',
          itemImg2: 'assets/r151.jpg',
          itemImg3: 'assets/r152.jpg',
          engine_capacity: '155 cc',
          mileage: '51.4 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '141 kg',
          fuel_tank_capacity: '11 litres',
          seat_height: '815 mm',
          rating: '4.7'
        },
        {
          item_id: 'Honda Livo',
          desc: "powered by 109.51cc BS6 engine which develops a power of 8.67 bhp and a torque of 9.30 Nm.",
          company: 'Honda',
          model_name: 'Honda Livo',
          price: '₹ 92,082',
          color: 'Grey, Red, Blue',
          color1: 'Grey',
          color2: 'Red',
          color3: 'Blue',
          itemImg: 'assets/livo.jpg',
          itemImg1: 'assets/livo1.jpg',
          itemImg2: 'assets/livo2.jpg',
          itemImg3: 'assets/livo3.jpg',
          engine_capacity: '109.51 cc',
          mileage: '60 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '113 kg',
          fuel_tank_capacity: '9 litres',
          seat_height: '790 mm',
          rating: '4.4'
        },
        {
          item_id: 'Suzuki Hayabusa',
          desc: "powered by 1340 cc engine. This Hayabusa engine generates a power of 190 PS @ 9700 rpm and a torque of 150 Nm @ 7000 rpm.",
          company: 'Suzuki',
          model_name: 'Suzuki Hayabusa',
          price: '₹ 20,91,784',
          color: 'White, Black, Grey',
          color1: 'White',
          color2: 'Grey',
          color3: 'Black',
          itemImg: 'assets/hayabusa.jpg',
          itemImg1: 'assets/hayabusa1.jpg',
          itemImg2: 'assets/hayabusa2.jpg',
          itemImg3: 'assets/hayabusa3.jpg',
          engine_capacity: '1,340 cc',
          mileage: '18 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '266 kg',
          fuel_tank_capacity: '20 litres',
          seat_height: '800 mm',
          rating: '4.6'
        },
        {
          item_id: 'Yamaha Fazer',
          desc: "powered by 149cc, 4-stroke, single-cylinder engine which develops 12.9bhp and 12.8Nm of torque through a five-speed gearbox.",
          company: 'Yamaha',
          model_name: 'Yamaha Fazer FI V 2.0',
          price: '₹ 89,643',
          color: 'Red, Steel, Black',
          color1: 'Red',
          color2: 'Steel',
          color3: 'Black',
          itemImg: 'assets/fazer.jpg',
          itemImg1: 'assets/fazer.jpg',
          itemImg2: 'assets/fazer2.jpg',
          itemImg3: 'assets/fazer3.jpg',
          engine_capacity: '149 cc',
          mileage: '45 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '137 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '790 mm',
          rating: '4.5'
        },
        {
          item_id: 'Ducati Multistrada V4',
          desc: "powered by 1158cc BS6 engine which develops a power of 167.62 bhp and a torque of 125 Nm.",
          company: 'Ducati',
          model_name: 'Ducati Multistrada V4',
          price: '₹ 24,99,509',
          color: 'Red, Grey, White',
          color1: 'Red',
          color2: 'Grey',
          color3: 'White',
          itemImg: 'assets/multistradav4.jpg',
          itemImg1: 'assets/multistradav41.jpg',
          itemImg2: 'assets/multistradav42.jpg',
          itemImg3: 'assets/multistradav43.jpg',
          engine_capacity: '1,158 cc',
          mileage: '15 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '240 kg',
          fuel_tank_capacity: '22 litres',
          seat_height: '840 mm',
          rating: '3'
        },
        {
          item_id: 'Triumph Scrambler 900',
          desc: "powered by a BS6-compliant 900cc liquid-cooled parallel-twin motor producing 65PS and 80Nm.",
          company: 'Triumph',
          model_name: 'Triumph Scrambler 900',
          price: '₹ 11,49,908',
          color: 'Red, Green, Black',
          color1: 'Red',
          color2: 'Green',
          color3: 'Black',
          itemImg: 'assets/rocket3.jpg',
          itemImg1: 'assets/rocket31.jpg',
          itemImg2: 'assets/rocket32.jpg',
          itemImg3: 'assets/rocket33.jpg',
          engine_capacity: '900 cc',
          mileage: '23 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '223 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '790 mm',
          rating: '5'
        },
        {
          item_id: 'Royal Enfield Himalayan',
          desc: "powered by 411 cc engine. This Himalayan engine generates a power of 24.31 PS @ 6500 rpm and a torque of 32 Nm @ 4000 - 4500 rpm.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Himalayan',
          price: '₹ 2,65,760',
          color: 'Grey, Black, Brown',
          color1: 'Grey',
          color2: 'Brown',
          color3: 'Black',
          itemImg: 'assets/himalayan.jpg',
          itemImg1: 'assets/himalayan1.jpg',
          itemImg2: 'assets/himalayan2.jpg',
          itemImg3: 'assets/himalayan3.jpg',
          engine_capacity: '411 cc',
          mileage: '31 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '199 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '800 mm',
          rating: '4.5'
        },
        {
          item_id: 'BMW F850 GS',
          desc: "powered by 853cc BS6 engine which develops a power of 93.87 bhp and a torque of 92 Nm.",
          company: 'BMW',
          model_name: 'BMW F850 GS',
          price: '₹ 15,13,986',
          color: 'Blue, White, Brown',
          color1: 'Blue',
          color2: 'Brown',
          color3: 'White',
          itemImg: 'assets/f850gs.jpg',
          itemImg1: 'assets/f850gs1.jpg',
          itemImg2: 'assets/f850gs2.jpg',
          itemImg3: 'assets/f850gs3.jpg',
          engine_capacity: '853 cc',
          mileage: '24 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '233 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '860 mm',
          rating: '4.8'
        },
        {
          item_id: 'Hero Passion Pro',
          desc: "powered by a single-cylinder, air-cooled, 113.2cc, fuel-injection engine, linked to a 4-speed gearbox.",
          company: 'Hero',
          model_name: 'Hero Passion Pro',
          price: '₹ 91,231',
          color: 'Red, Yellow, Black',
          color1: 'Red',
          color2: 'Yellow',
          color3: 'Black',
          itemImg: 'assets/passionpro.jpg',
          itemImg1: 'assets/passionpro.jpg',
          itemImg2: 'assets/passionpro1.jpg',
          itemImg3: 'assets/passionpro2.jpg',
          engine_capacity: '113.2 cc',
          mileage: '55 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '117 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '799 mm',
          rating: '4.5'
        },
        {
          item_id: 'TVS Star City',
          desc: "powered by 109.7cc BS6 engine which develops a power of 8.08 bhp and a torque of 8.7 Nm.",
          company: 'TVS',
          model_name: 'TVS Star City Plus',
          price: '₹ 90,394',
          color: '(Red, Blue, Grey) in Black',
          color1: 'Red in Black',
          color2: 'Blue in Black',
          color3: 'Grey in Black',
          itemImg: 'assets/starcity.jpg',
          itemImg1: 'assets/starcity1.jpg',
          itemImg2: 'assets/starcity2.jpg',
          itemImg3: 'assets/starcity3.jpg',
          engine_capacity: '109.7 cc',
          mileage: '68 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '115 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '785 mm',
          rating: '4.4'
        },
        {
          item_id: 'Triumph Rocket 3',
          desc: "powered by 2458cc BS6 engine which develops a power of 165 bhp and a torque of 221 Nm.",
          company: 'Triumph',
          model_name: 'Triumph Rocket 3',
          price: '₹ 23,50,140',
          color: 'Red, Grey, Black',
          color1: 'Red',
          color2: 'Grey',
          color3: 'Black',
          itemImg: 'assets/rocket3.jpg',
          itemImg1: 'assets/rocket31.jpg',
          itemImg2: 'assets/rocket32.jpg',
          itemImg3: 'assets/rocket33.jpg',
          engine_capacity: '2,458 cc',
          mileage: '14.6 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '304 kg',
          fuel_tank_capacity: '18 litres',
          seat_height: '773 mm',
          rating: '4.6'
        },
        {
          item_id: 'Ducati Monster BS6',
          desc: "powered by 937cc BS6 engine which develops a power of 109.96 bhp and a torque of 93 Nm.",
          company: 'Ducati',
          model_name: 'Ducati Monster BS6',
          price: '₹ 14,09,494',
          color: 'Red, Grey, Black',
          color1: 'Red',
          color2: 'Grey',
          color3: 'Black',
          itemImg: 'assets/monsterbs6.jpg',
          itemImg1: 'assets/monsterbs61.jpg',
          itemImg2: 'assets/monsterbs62.jpg',
          itemImg3: 'assets/monsterbs63.jpg',
          engine_capacity: '937 cc',
          mileage: '19 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '188 kg',
          fuel_tank_capacity: '14 litres',
          seat_height: '820 mm',
          rating: '4.6'
        },
        {
          item_id: 'BMW S 1000 RR',
          desc: "powered by 1170cc BS6 engine which develops a power of 107.28 bhp and a torque of 116 Nm.",
          company: 'BMW',
          model_name: 'BMW S 1000 RR',
          price: '₹ 23,86,743',
          color: 'Red, White, Black',
          color1: 'Red',
          color2: 'White',
          color3: 'Black',
          itemImg: 'assets/s1000rr.jpg',
          itemImg1: 'assets/s1000rr1.jpg',
          itemImg2: 'assets/s1000rr2.jpg',
          itemImg3: 'assets/s1000rr3.jpg',
          engine_capacity: '999 cc',
          mileage: '16 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '197 kg',
          fuel_tank_capacity: '16.5 litres',
          seat_height: '824 mm',
          rating: '4.8'
        },
        {
          item_id: 'Harley-Davidson Fat Bob',
          desc: "powered by a 1868 cc air-cooled engine which produces 93.8 PS @ 5020 rpm of power.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Fat Bob',
          price: '₹ 23,85,592',
          color: 'Red, Black, Grey',
          color1: 'Red',
          color2: 'Grey',
          color3: 'Black',
          itemImg: 'assets/fatbob.jpg',
          itemImg1: 'assets/fatbob.jpg',
          itemImg2: 'assets/fatbob2.jpg',
          itemImg3: 'assets/fatbob3.jpg',
          engine_capacity: '1,868 cc',
          mileage: '18 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '306 kg',
          fuel_tank_capacity: '13.2 litres',
          seat_height: '710 mm',
          rating: '4.9'
        },
        {
          item_id: 'Hero Passion Plus',
          desc: "powered by a 97.2cc air-cooled single-cylinder engine producing 8PS and 8.05Nm.",
          company: 'Hero',
          model_name: 'Hero Passion Plus',
          price: '₹ 93,324',
          color: 'Red, Blue, Black',
          color1: 'Red',
          color2: 'Blue',
          color3: 'Black',
          itemImg: 'assets/passionplus.jpg',
          itemImg1: 'assets/passionplus.jpg',
          itemImg2: 'assets/passionplus1.jpg',
          itemImg3: 'assets/passionplus2.jpg',
          engine_capacity: '97.2 cc',
          mileage: '55 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '115 kg',
          fuel_tank_capacity: '11 litres',
          seat_height: '790 mm',
          rating: '4.6'
        },
        {
          item_id: 'Triumph Tiger 900',
          desc: "powered by 888cc BS6 engine which develops a power of 93.9 bhp and a torque of 87 Nm.",
          company: 'Triumph',
          model_name: 'Triumph Tiger 900',
          price: '₹ 16,32,724',
          color: 'Red, White, Black',
          color1: 'Red',
          color2: 'White',
          color3: 'Black',
          itemImg: 'assets/tiger900.jpg',
          itemImg1: 'assets/tiger9001.jpg',
          itemImg2: 'assets/tiger9002.jpg',
          itemImg3: 'assets/tiger9003.jpg',
          engine_capacity: '888 cc',
          mileage: '23.55 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '194 kg',
          fuel_tank_capacity: '20 litres',
          seat_height: '820 mm',
          rating: '4.5'
        },
        {
          item_id: 'KTM Duke',
          desc: "powered by a 248.76 cc air-cooled engine which produces 30 PS @ 9000 rpm of power.",
          company: 'KTM',
          model_name: 'KTM 250 Duke',
          price: '₹ 2,38,436',
          color: 'Orange, White, Black',
          color1: 'Orange',
          color2: 'Black',
          color3: 'White',
          itemImg: 'assets/duke.jpg',
          itemImg1: 'assets/duke1.jpg',
          itemImg2: 'assets/duke2.jpg',
          itemImg3: 'assets/duke3.jpg',
          engine_capacity: '162.7 cc',
          mileage: '50 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '140 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '798 mm',
          rating: '4.9'
        },
        {
          item_id: 'Harley-Davidson Nightster',
          desc: "powered by 975cc BS6 engine which develops a power of 88.5 bhp and a torque of 95 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Nightster',
          price: '₹ 20,40,391',
          color: 'Maroon, Blue, Yellow',
          color1: 'Maroon',
          color2: 'Blue',
          color3: 'Yellow',
          itemImg: 'assets/nightster.jpg',
          itemImg1: 'assets/nightster.jpg',
          itemImg2: 'assets/nightster1.jpg',
          itemImg3: 'assets/nightster2.jpg',
          engine_capacity: '975 cc',
          mileage: '18 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '221 kg',
          fuel_tank_capacity: '11.7 litres',
          seat_height: '705 mm',
          rating: '4'
        },
        {
          item_id: 'TVS Raider',
          desc: "powered by 124.8cc BS6 engine which develops a power of 11.2 bhp and a torque of 11.2 Nm.",
          company: 'TVS',
          model_name: 'TVS Raider 125',
          price: '₹ 1,05,964',
          color: 'Yelow, Blue, Red',
          color1: 'Red',
          color2: 'Blue',
          color3: 'Yellow',
          itemImg: 'assets/raider.jpg',
          itemImg1: 'assets/raider.jpg',
          itemImg2: 'assets/raider1.jpg',
          itemImg3: 'assets/raider2.jpg',
          engine_capacity: '124.8 cc',
          mileage: '56.7 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '123 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '780 mm',
          rating: '4.3'
        },
        {
          item_id: 'Hero HF Deluxe',
          desc: "powered by 97.2cc BS6 engine which develops a power of 7.91 bhp and a torque of 8.05 Nm.",
          company: 'Hero',
          model_name: 'Hero HF Deluxe',
          price: '₹ 72,305',
          color: '(Red, Blue, Purple) in Black',
          color1: 'Red in Black',
          color2: 'Blue in Black',
          color3: 'Purple in Black',
          itemImg: 'assets/hfdeluxe.jpg',
          itemImg1: 'assets/hfdeluxe.jpg',
          itemImg2: 'assets/hfdeluxe1.jpg',
          itemImg3: 'assets/hfdeluxe2.jpg',
          engine_capacity: '97.2 cc',
          mileage: '65 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '110 kg',
          fuel_tank_capacity: '9.1 litres',
          seat_height: '805 mm',
          rating: '4.5'
        },
        {
          item_id: 'BMW G310',
          desc: "powered by a 313 cc air-cooled engine which produces 33.99 PS @ 9700 rpm of power.",
          company: 'BMW',
          model_name: 'BMW G310 RR',
          price: '₹ 2,99,495',
          color: '(White, Black) in red, Black',
          color1: 'White in red',
          color2: 'Black in red',
          color3: 'Black',
          itemImg: 'assets/g310.jpg',
          itemImg1: 'assets/g3101.jpg',
          itemImg2: 'assets/g3102.jpg',
          itemImg3: 'assets/g3103.jpg',
          engine_capacity: '162.7 cc',
          mileage: '50 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '140 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '798 mm',
          rating: '4.6'
        },
        {
          item_id: 'Royal Enfield Meteor',
          desc: "powered by 349cc BS6 engine which develops a power of 20.2 bhp and a torque of 27 Nm.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Meteor 350',
          price: '₹ 2,43,283',
          color: 'Red, Blue, Yellow',
          color1: 'Red',
          color2: 'Blue',
          color3: 'Yellow',
          itemImg: 'assets/meteor.jpg',
          itemImg1: 'assets/meteor.jpg',
          itemImg2: 'assets/meteor1.jpg',
          itemImg3: 'assets/meteor2.jpg',
          engine_capacity: '349 cc',
          mileage: '32.6 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '191 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '765 mm',
          rating: '4.5'
        },
        {
          item_id: 'Honda SP 125',
          desc: "powered by 124cc BS6 engine which develops a power of 10.72 bhp and a torque of 10.9 Nm.",
          company: 'Honda',
          model_name: 'Honda SP 125',
          price: '₹ 1,03,875',
          color: 'Grey, Red, Black',
          color1: 'Red',
          color2: 'Black',
          color3: 'Grey',
          itemImg: 'assets/sp125.jpg',
          itemImg1: 'assets/sp1251.jpg',
          itemImg2: 'assets/sp1252.jpg',
          itemImg3: 'assets/sp1253.jpg',
          engine_capacity: '124 cc',
          mileage: '65 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '116 kg',
          fuel_tank_capacity: '11.2 litres',
          seat_height: '790 mm',
          rating: '4.4'
        },
        {
          item_id: 'Suzuki V-Strom SX',
          desc: "powered by 249cc BS6 engine which develops a power of 26.1 bhp and a torque of 22.2 Nm.",
          company: 'Suzuki',
          model_name: 'Suzuki V-Strom SX',
          price: '₹ 2,51,140',
          color: 'Orange, Black, Yellow',
          color1: 'Orange',
          color2: 'Black',
          color3: 'Yellow',
          itemImg: 'assets/vstrom.jpg',
          itemImg1: 'assets/vstrom1.jpg',
          itemImg2: 'assets/vstrom2.jpg',
          itemImg3: 'assets/vstrom3.jpg',
          engine_capacity: '249 cc',
          mileage: '36 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '167 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '835 mm',
          rating: '4.8'
        },
        {
          item_id: 'Kawasaki Ninja',
          desc: "powered by 399cc BS6 engine which develops a power of 44.7 bhp and a torque of 37 Nm.",
          company: 'Kawasaki',
          model_name: 'Kawasaki Ninja 400',
          price: '₹ 5,18,991',
          color: 'Green, Black, Grey',
          color1: 'Green',
          color2: 'Black',
          color3: 'Grey',
          itemImg: 'assets/ninja.jpg',
          itemImg1: 'assets/ninja.jpg',
          itemImg2: 'assets/ninja2.jpg',
          itemImg3: 'assets/ninja3.jpg',
          engine_capacity: '399 cc',
          mileage: '26.7 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '168 kg',
          fuel_tank_capacity: '14 litres',
          seat_height: '785 mm',
          rating: '4.8'
        },
        {
          item_id: 'Triumph Speed 400',
          desc: "powered by 398.15cc BS6 engine which develops a power of 39.5 bhp and a torque of 37.5 Nm.",
          company: 'Triumph',
          model_name: 'Triumph Speed 400',
          price: '₹ 2,71,737',
          color: 'Red, Blue, Black',
          color1: 'Red',
          color2: 'Black',
          color3: 'Blue',
          itemImg: 'assets/speed400.jpg',
          itemImg1: 'assets/speed4001.jpg',
          itemImg2: 'assets/speed4002.jpg',
          itemImg3: 'assets/speed4003.jpg',
          engine_capacity: '398.15 cc',
          mileage: '29.8 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '176 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '790 mm',
          rating: '4.8'
        },
        {
          item_id: 'Hero Super Splendor',
          desc: "powered by 124.7cc BS6 engine which develops a power of 10.72 bhp and a torque of 10.6 Nm.",
          company: 'Hero',
          model_name: 'Hero Super Splendor',
          price: '₹ 1,01,190',
          color: 'Red, Blue, Black',
          color1: 'Red',
          color2: 'Black',
          color3: 'Blue',
          itemImg: 'assets/supersplender.jpg',
          itemImg1: 'assets/supersplender.jpg',
          itemImg2: 'assets/supersplender1.jpg',
          itemImg3: 'assets/supersplender2.jpg',
          engine_capacity: '124.7 cc',
          mileage: '55 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '122 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '799 mm',
          rating: '4.4'
        },
        {
          item_id: 'Norton Dominator',
          desc: "powered by the same 961cc parallel-twin cylinder engine that is air/oil cooled as the Commando 961.",
          company: 'Norton',
          model_name: 'Norton Dominator',
          price: '₹ 23,70,000',
          color: 'Grey',
          itemImg: 'assets/dominator.jpg',
          engine_capacity: '961 cc',
          mileage: '14 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '227 kg',
          fuel_tank_capacity: '17 litres',
          seat_height: '810 mm'
        },
        {
          item_id: 'TVS Sport',
          desc: "powered by 109.7cc BS6 engine which develops a power of 8.18 bhp and a torque of 8.7 Nm.",
          company: 'TVS',
          model_name: 'TVS Sport',
          price: '₹ 79,502',
          color: 'Black, Purple, Grey',
          color1: 'Purple',
          color2: 'Black',
          color3: 'Grey',
          itemImg: 'assets/sport.jpg',
          itemImg1: 'assets/sport.jpg',
          itemImg2: 'assets/sport1.jpg',
          itemImg3: 'assets/sport2.jpg',
          engine_capacity: '109.7 cc',
          mileage: '68 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '112 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '790 mm',
          rating: '4.3'
        },
        {
          item_id: 'Honda Hornet',
          desc: "powered by 184.4cc BS6 engine which develops a power of 17.03 bhp and a torque of 16.1 Nm.",
          company: 'Honda',
          model_name: 'Honda Hornet 2.0',
          price: '₹ 1,65,427',
          color: 'Grey, Red, Blue',
          color1: 'Grey',
          color2: 'Red',
          color3: 'Blue',
          itemImg: 'assets/hornet.jpg',
          itemImg1: 'assets/hornet1.jpg',
          itemImg2: 'assets/hornet2.jpg',
          itemImg3: 'assets/hornet3.jpg',
          engine_capacity: '184.4 cc',
          mileage: '42.3 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '142 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '790 mm',
          rating: '4.1'
        },
        {
          item_id: 'Aprilia Tuono 660',
          desc: "powered by 659cc BS6 engine which develops a power of 93.87 bhp and a torque of 67 Nm.",
          company: 'Aprilia',
          model_name: 'Aprilia Tuono 660',
          price: '₹ 15,15,436',
          color: 'Black, Grey, Green',
          color1: 'Grey',
          color2: 'Black',
          color3: 'Green',
          itemImg: 'assets/tuono660.jpg',
          itemImg1: 'assets/tuono6601.jpg',
          itemImg2: 'assets/tuono6602.jpg',
          itemImg3: 'assets/tuono6603.jpg',
          engine_capacity: '659 cc',
          mileage: '20.4 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '183 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '	820 mm',
          rating: '5'
        },
        {
          item_id: 'Royal Enfield Scram',
          desc: "powered by 411cc BS6 engine which develops a power of 24.3 bhp and a torque of 32 Nm.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Scram 411',
          price: '₹ 2,54,894',
          color: '(Red, Blue, Yellow) in Grey',
          color1: 'Red in Grey',
          color2: 'Blue in Grey',
          color3: 'Yellow in Grey',
          itemImg: 'assets/scram.jpg',
          itemImg1: 'assets/scram.jpg',
          itemImg2: 'assets/scram1.jpg',
          itemImg3: 'assets/scram2.jpg',
          engine_capacity: '411 cc',
          mileage: '29.6 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '185 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '795 mm',
          rating: '4.5'
        },
        {
          item_id: 'Harley-Davidson Road Glide',
          desc: "powered by 1868cc BS6 engine which develops a power of 92.5 bhp and a torque of 158 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Road Glide Special',
          price: '₹ 46,99,935',
          color: 'Black, Orange, Maroon',
          color1: 'Black',
          color2: 'Orange',
          color3: 'Maroon',
          itemImg: 'assets/roadglide.jpg',
          itemImg1: 'assets/roadglide.jpg',
          itemImg2: 'assets/roadglide1.jpg',
          itemImg3: 'assets/roadglide2.jpg',
          engine_capacity: '1,868 cc',
          mileage: '16 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '387 kg',
          fuel_tank_capacity: '22.7 litres',
          seat_height: '695 mm',
          rating: '4'
        },
        {
          item_id: 'Mahindra Centuro',
          desc: "powered by a 106.7cc single-cylinder air-cooled engine.",
          company: 'Mahindra',
          model_name: 'Mahindra Centuro',
          price: '₹ 50,507',
          color: 'Red, White, Black',
          color1: 'Black',
          color2: 'Red',
          color3: 'White',
          itemImg: 'assets/centuro.jpg',
          itemImg1: 'assets/centuro1.jpg',
          itemImg2: 'assets/centuro2.jpg',
          itemImg3: 'assets/centuro3.jpg',
          engine_capacity: '106.7 cc',
          mileage: '60 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '126 kg',
          fuel_tank_capacity: '12.7 litres',
          seat_height: '800 mm',
          rating: '3.1'
        },
        {
          item_id: 'Honda CD 110 Dream',
          desc: "powered by 109.51cc BS6 engine which develops a power of 8.67 bhp and a torque of 9.30 Nm.",
          company: 'Honda',
          model_name: 'Honda CD 110 Dream',
          price: '₹ 87,026',
          color: '(Grey, Red, Blue) in Black',
          color1: 'Grey in Black',
          color2: 'Red in Black',
          color3: 'White in Black',
          itemImg: 'assets/cd110.jpg',
          itemImg1: 'assets/cd1101.jpg',
          itemImg2: 'assets/cd1102.jpg',
          itemImg3: 'assets/cd1103.jpg',
          engine_capacity: '109.51 cc',
          mileage: '62 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '112 kg',
          fuel_tank_capacity: '9.1 litres',
          seat_height: '790 mm',
          rating: '4.2'
        },
        {
          item_id: 'Tork Kratos',
          desc: "Powered by a N/A cc engine, the Kratos is available in 2 variants.",
          company: 'Tork',
          model_name: 'Tork Kratos',
          price: '₹ 1,30,832',
          color: 'Black, Red, White',
          color1: 'Black',
          color2: 'Red',
          color3: 'White',
          itemImg: 'assets/kratos.jpg',
          itemImg1: 'assets/kratos1.jpg',
          itemImg2: 'assets/kratos2.jpg',
          itemImg3: 'assets/kratos3.jpg',
          engine_capacity: 'N/A',
          mileage: '120 Kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '140 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '785 mm',
          rating: '4.5'
        },
        {
          item_id: 'Harley-Davidson PAN',
          desc: "powered by 1252cc BS6 engine which develops a power of 150.19 bhp and a torque of 128 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson PAN America 1250',
          price: '₹ 28,45,861',
          color: 'Black, Yellow, Grey',
          color1: 'Black',
          color2: 'Yellow',
          color3: 'Grey',
          itemImg: 'assets/panamerica.jpg',
          itemImg1: 'assets/panamerica.jpg',
          itemImg2: 'assets/panamerica1.jpg',
          itemImg3: 'assets/panamerica2.jpg',
          engine_capacity: '1,252 cc',
          mileage: '18.2 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '258 kg',
          fuel_tank_capacity: '21.2 litres',
          seat_height: '807 mm',
          rating: '4.6'
        },
        {
          item_id: 'Benelli Imperiale 400',
          desc: "powered by 249cc BS6 engine which develops a power of 25.47 bhp and a torque of 21.1 Nm.",
          company: 'Benelli',
          model_name: 'Benelli Imperiale 400',
          price: '₹ 2,97,621',
          color: 'Steel, Red, Black',
          color1: 'Black',
          color2: 'Steel',
          color3: 'Red',
          itemImg: 'assets/imperiale400.jpg',
          itemImg1: 'assets/imperiale4001.jpg',
          itemImg2: 'assets/imperiale4002.jpg',
          itemImg3: 'assets/imperiale4003.jpg',
          engine_capacity: '374 cc',
          mileage: '31 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '205 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '780 mm',
          rating: '3.8'
        },
        {
          item_id: 'Suzuki Hayate',
          desc: "powered by 113cc single-cylinder, air-cooled engine that produces 8.58 Bhp of power at 7,500 rpm along with 9.3 Nm of torque at 5,500 rpm.",
          company: 'Suzuki',
          model_name: 'Suzuki Hayate EP',
          price: '₹ 54,603',
          color: 'Red, Black, Grey',
          color1: 'Black',
          color2: 'Grey',
          color3: 'Red',
          itemImg: 'assets/hayate.jpg',
          itemImg1: 'assets/hayate1.jpg',
          itemImg2: 'assets/hayate2.jpg',
          itemImg3: 'assets/hayate3.jpg',
          engine_capacity: '113 cc',
          mileage: '60 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '107 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '795 mm',
          rating: '4.2'
        },
        {
          item_id: 'Honda X-Blade',
          desc: "powered by 162.71cc BS6 engine which develops a power of 13.67 bhp and a torque of 14.7 Nm.",
          company: 'Honda',
          model_name: 'Honda X-Blade',
          price: '₹ 1,43,078',
          color: 'Grey, Red, Blue',
          color1: 'Blue',
          color2: 'Grey',
          color3: 'Red',
          itemImg: 'assets/xblade.jpg',
          itemImg1: 'assets/xblade1.jpg',
          itemImg2: 'assets/xblade2.jpg',
          itemImg3: 'assets/xblade3.jpg',
          engine_capacity: '162.71 cc',
          mileage: '50 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '143 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '795 mm',
          rating: '4.5'
        },
        {
          item_id: 'Revolt RV',
          desc: " powered by 3000 watt Mid Drive Motor. The Revolt RV400 takes 4.5 Hours to get fully charged.",
          company: 'Revolt',
          model_name: 'Revolt RV 400',
          price: '₹ 1,35,189',
          color: 'Steel, Black, Red',
          color1: 'Steel',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/rv.jpg',
          itemImg1: 'assets/rv1.jpg',
          itemImg2: 'assets/rv2.jpg',
          itemImg3: 'assets/rv3.jpg',
          engine_capacity: '125 cc',
          mileage: '156 kmpl',
          transmission: 'Automatic',
          kerb_weight: '108 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '814 mm',
          rating: '4.2'
        },
        {
          item_id: 'Harley-Davidson Street Glide',
          desc: "powered by 1868cc BS6 engine which develops a power of 92.5 bhp and a torque of 158 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Street Glide Special',
          price: '₹ 43,54,733',
          color: 'Black, Orange, Maroon',
          color1: 'Orange',
          color2: 'Black',
          color3: 'Maroon',
          itemImg: 'assets/streetglide.jpg',
          itemImg1: 'assets/streetglide.jpg',
          itemImg2: 'assets/streetglide1.jpg',
          itemImg3: 'assets/streetglide2.jpg',
          engine_capacity: '1,868 cc',
          mileage: '16 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '375 kg',
          fuel_tank_capacity: '22.7 litres',
          seat_height: '690 mm',
          rating: '4'
        },
        {
          item_id: 'BMW K 1600',
          desc: "powered by 853cc BS6 engine which develops a power of 93.87 bhp and a torque of 92 Nm.",
          company: 'BMW',
          model_name: 'BMW K 1600',
          price: '₹ 41,84,337',
          color: 'Blue, White, Grey',
          color1: 'Blue',
          color2: 'White',
          color3: 'Grey',
          itemImg: 'assets/k1600.jpg',
          itemImg1: 'assets/k16001.jpg',
          itemImg2: 'assets/k16002.jpg',
          itemImg3: 'assets/k16003.jpg',
          engine_capacity: '1,649 cc',
          mileage: '17 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '358 kg',
          fuel_tank_capacity: '26.5 litres',
          seat_height: '750 mm',
          rating: '4.6'
        },
        {
          item_id: 'TVS Radeon',
          desc: "powered by 109.7cc BS6 engine which develops a power of 8.08 bhp and a torque of 8.7 Nm.",
          company: 'TVS',
          model_name: 'TVS Radeon',
          price: '₹ 89,499',
          color: 'Blue, Black, Red',
          color1: 'Blue',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/radeon.jpg',
          itemImg1: 'assets/radeon.jpg',
          itemImg2: 'assets/radeon1.jpg',
          itemImg3: 'assets/radeon2.jpg',
          engine_capacity: '109.7 cc',
          mileage: '65 kmpl',
          transmission: '4 Speed Manual',
          kerb_weight: '113 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '780 mm',
          rating: '4.4'
        },
        {
          item_id: 'Royal Enfield Hunter',
          desc: "powered by 349.34cc BS6 engine which develops a power of 20.2 bhp and a torque of 27 Nm.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Hunter 350',
          price: '₹ 2,43,283',
          color: 'Red, Blue, Black',
          color1: 'Blue',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/hunter.jpg',
          itemImg1: 'assets/hunter1.jpg',
          itemImg2: 'assets/hunter2.jpg',
          itemImg3: 'assets/hunter3.jpg',
          engine_capacity: '349.34 cc',
          mileage: '36 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '177 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '800 mm',
          rating: '4.6'
        },
        {
          item_id: 'Harley-Davidson Sportster',
          desc: "powered by 1252cc BS6 engine which develops a power of 120.69 bhp and a torque of 125 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Sportster S',
          price: '₹ 21,89,978',
          color: 'Black, Blue, Grey',
          color1: 'Blue',
          color2: 'Black',
          color3: 'Grey',
          itemImg: 'assets/sportster.jpg',
          itemImg1: 'assets/sportster.jpg',
          itemImg2: 'assets/sportster1.jpg',
          itemImg3: 'assets/sportster2.jpg',
          engine_capacity: '1,252 cc',
          mileage: '20 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '225 kg',
          fuel_tank_capacity: '11.8 litres',
          seat_height: '765 mm',
          rating: '4.3'
        },
        {
          item_id: 'Bajaj CT 125X',
          desc: " powered by 124.4cc BS6 engine which develops a power of 10.7 bhp and a torque of 11 Nm.",
          company: 'Bajaj',
          model_name: 'Bajaj CT 125X',
          price: '₹  91,779',
          color: '(Red, Green, Blue) in Black',
          color1: 'Red in Black',
          color2: 'Green in Black',
          color3: 'Blue in Black',
          itemImg: 'assets/ct125x.jpg',
          itemImg1: 'assets/ct125x.jpg',
          itemImg2: 'assets/ct125x1.jpg',
          itemImg3: 'assets/ct125x2.jpg',
          engine_capacity: '124.4 cc',
          mileage: '60 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '130 kg',
          fuel_tank_capacity: '11 litres',
          seat_height: '810 mm',
          rating: '4.6'
        },
        {
          item_id: 'Hero Glamour',
          desc: "powered by a 124.7 cc air-cooled engine which produces 10.84 PS @ 7500 rpm of power.",
          company: 'Hero',
          model_name: 'Hero Glamour',
          price: '₹ 98,106',
          color: '(Red, Blue, Golden) in Black',
          color1: 'Red in Black',
          color2: 'Golden in Black',
          color3: 'Blue in Black',
          itemImg: 'assets/glamour.jpg',
          itemImg1: 'assets/glamour.jpg',
          itemImg2: 'assets/glamour1.jpg',
          itemImg3: 'assets/glamour2.jpg',
          engine_capacity: '124.7 cc',
          mileage: '55 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '122 kg',
          fuel_tank_capacity: '10 litres',
          seat_height: '793 mm',
          rating: '4'
        },
        {
          item_id: 'Triumph Street Triple RS',
          desc: "powered by 765cc BS6 engine which develops a power of 128.2 bhp and a torque of 80 Nm.",
          company: 'Triumph',
          model_name: 'Triumph Street Triple RS',
          price: '₹ 14,12,727',
          color: 'Red, Grey, Yellow',
          color1: 'Red',
          color2: 'Grey',
          color3: 'Yellow',
          itemImg: 'assets/tripplers.jpg',
          itemImg1: 'assets/tripplers1.jpg',
          itemImg2: 'assets/tripplers2.jpg',
          itemImg3: 'assets/tripplers3.jpg',
          engine_capacity: '765 cc',
          mileage: '19.2 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '166 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '836 mm',
          rating: '5'
        },
        {
          item_id: 'Honda Hness CB350',
          desc: "powered by 348.36cc BS6 engine which develops a power of 20.78 bhp and a torque of 30 Nm.",
          company: 'Honda',
          model_name: 'Honda CB350RS',
          price: '₹ 2,52,414',
          color: 'Grey, Red, Olive',
          color1: 'Red',
          color2: 'Grey',
          color3: 'Olive',
          itemImg: 'assets/hness.jpg',
          itemImg1: 'assets/hness.jpg',
          itemImg2: 'assets/hness1.jpg',
          itemImg3: 'assets/hness2.jpg',
          engine_capacity: '348.36 cc',
          mileage: '35 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '181 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '800 mm',
          rating: '4.7'
        },
        {
          item_id: 'Benelli TRK 251',
          desc: "powered by 249cc BS6 engine which develops a power of 25.47 bhp and a torque of 21.1 Nm.",
          company: 'Benelli',
          model_name: 'Benelli TRK 251',
          price: '₹ 3,72,164',
          color: 'White, Grey, Black',
          color1: 'White',
          color2: 'Grey',
          color3: 'Black',
          itemImg: 'assets/trk251.jpg',
          itemImg1: 'assets/trk2511.jpg',
          itemImg2: 'assets/trk2512.jpg',
          itemImg3: 'assets/trk2513.jpg',
          engine_capacity: '249 cc',
          mileage: '30 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '164 kg',
          fuel_tank_capacity: '18 litres',
          seat_height: '800 mm',
          rating: '4'
        },
        {
          item_id: 'Moto Guzzi V85 TT',
          desc: "powered by a 853 cc air-cooled engine which produces 76 PS @ 7500 rpm of power.",
          company: 'Moto Guzzi',
          model_name: 'Moto Guzzi V85 TT',
          price: '₹ 17,97,818',
          color: 'Black, Red, Steel',
          color1: 'Red',
          color2: 'Steel',
          color3: 'Black',
          itemImg: 'assets/v85tt.jpg',
          itemImg1: 'assets/v85tt.jpg',
          itemImg2: 'assets/v85tt2.jpg',
          itemImg3: 'assets/v85tt3.jpg',
          engine_capacity: '853 cc',
          mileage: '23.8 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '230 kg',
          fuel_tank_capacity: '23 litres',
          seat_height: '828 mm',
          rating: '5'
        },
        {
          item_id: 'Hero Xpulse',
          desc: "powered by 199.6cc BS6 engine which develops a power of 18.9 bhp and a torque of 17.35 Nm.",
          company: 'Hero',
          model_name: 'Hero Xpulse 200 4V',
          price: '₹ 1,76,804',
          color: 'Red, White, Blue',
          color1: 'Red',
          color2: 'White',
          color3: 'Blue',
          itemImg: 'assets/xpulse.jpg',
          itemImg1: 'assets/xpulse.jpg',
          itemImg2: 'assets/xpulse1.jpg',
          itemImg3: 'assets/xpulse2.jpg',
          engine_capacity: '199.6 cc',
          mileage: '32.5 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '159 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '825 mm',
          rating: '4.5'
        },
        {
          item_id: 'Royal Enfield Continental',
          desc: "powered by 648cc BS6 engine which develops a power of 47 bhp and a torque of 52 Nm.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Continental GT 650',
          price: '₹ 3,83,623',
          color: 'Red, Blue, White',
          color1: 'Red',
          color2: 'White',
          color3: 'Blue',
          itemImg: 'assets/continental.jpg',
          itemImg1: 'assets/continental.jpg',
          itemImg2: 'assets/continental1.jpg',
          itemImg3: 'assets/continental2.jpg',
          engine_capacity: '648 cc',
          mileage: '25 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '211 kg',
          fuel_tank_capacity: '12.5 litres',
          seat_height: '804 mm',
          rating: '4.7'
        },
        {
          item_id: 'Aprilia RS 660',
          desc: "powered by 659cc BS6 engine which develops a power of 98.63 bhp and a torque of 67 Nm.",
          company: 'Aprilia',
          model_name: 'Aprilia RS 660',
          price: '₹ 15,49,668',
          color: 'Black, Green, Violet',
          color1: 'Black',
          color2: 'Green',
          color3: 'Violet',
          itemImg: 'assets/rs660.jpg',
          itemImg1: 'assets/rs6601.jpg',
          itemImg2: 'assets/rs6602.jpg',
          itemImg3: 'assets/rs6603.jpg',
          engine_capacity: '659 cc',
          mileage: '20.4 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '183 kg',
          fuel_tank_capacity: '15 litres',
          seat_height: '	820 mm',
          rating: '4.6'
        },
        {
          item_id: 'Bajaj Dominar',
          desc: "powered by a 248.77 cc air-cooled engine which produces 27 PS @ 8500 rpm of power.",
          company: 'Bajaj',
          model_name: 'Bajaj Dominar 250',
          price: '₹ 2,22,604',
          color: 'Red, Black, Green',
          color1: 'Black',
          color2: 'Green',
          color3: 'Red',
          itemImg: 'assets/dominar.jpg',
          itemImg1: 'assets/dominar.jpg',
          itemImg2: 'assets/dominar1.jpg',
          itemImg3: 'assets/dominar2.jpg',
          engine_capacity: '248.8 cc',
          mileage: '32 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '180 kg',
          fuel_tank_capacity: '13 litres',
          seat_height: '800 mm',
          rating: '4.4'
        },
        {
          item_id: 'Honda Shine',
          desc: "powered by 123.94cc BS6 engine which develops a power of 10.59 bhp and a torque of 11 Nm.",
          company: 'Honda',
          model_name: 'Honda Shine',
          price: '₹ 96,620',
          color: 'Black, Maroon, Blue',
          color1: 'Black',
          color2: 'Maroon',
          color3: 'Blue',
          itemImg: 'assets/shine.jpg',
          itemImg1: 'assets/shine1.jpg',
          itemImg2: 'assets/shine2.jpg',
          itemImg3: 'assets/shine3.jpg',
          engine_capacity: '123.94 cc',
          mileage: '55 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '114 kg',
          fuel_tank_capacity: '10.5 litres',
          seat_height: '791 mm',
          rating: '4.4'
        },
        {
          item_id: 'Harley-Davidson Heritage',
          desc: "powered by 1868cc BS6 engine which develops a power of 94 bhp and a torque of 155 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson Heritage Classic',
          price: '₹ 30,87,502',
          color: 'Black, Golden, Maroon',
          color1: 'Black',
          color2: 'Golden',
          color3: 'Maroon',
          itemImg: 'assets/heritage.jpg',
          itemImg1: 'assets/heritage.jpg',
          itemImg2: 'assets/heritage1.jpg',
          itemImg3: 'assets/heritage2.jpg',
          engine_capacity: '1,868 cc',
          mileage: '18 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '330 kg',
          fuel_tank_capacity: '18.9 litres',
          seat_height: '680 mm',
          rating: '4'
        },
        {
          item_id: 'Bajaj Platina',
          desc: "powered by 115.45cc BS6 engine which develops a power of 8.48 bhp and a torque of 9.81 Nm.",
          company: 'Bajaj',
          model_name: 'Bajaj Platina 110',
          price: '₹  88,273',
          color: 'Red, Black, Blue',
          color1: 'Black',
          color2: 'Red',
          color3: 'Blue',
          itemImg: 'assets/platina.jpg',
          itemImg1: 'assets/platina1.jpg',
          itemImg2: 'assets/platina2.jpg',
          itemImg3: 'assets/platina3.jpg',
          engine_capacity: '115.45 cc',
          mileage: '70 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '122 kg',
          fuel_tank_capacity: '11 litres',
          seat_height: '807 mm',
          rating: '4.3'
        },
        {
          item_id: 'Royal Enfield Interceptor',
          desc: "powered by 648cc BS6 engine which develops a power of 47 bhp and a torque of 52 Nm.",
          company: 'Royal Enfield',
          model_name: 'Royal Enfield Interceptor 650',
          price: '₹ 3,65,387',
          color: 'Red, Blue, Orange',
          color1: 'Orange',
          color2: 'Red',
          color3: 'Blue',
          itemImg: 'assets/interceptor.jpg',
          itemImg1: 'assets/interceptor.jpg',
          itemImg2: 'assets/interceptor1.jpg',
          itemImg3: 'assets/interceptor2.jpg',
          engine_capacity: '648 cc',
          mileage: '23 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '213 kg',
          fuel_tank_capacity: '13.7 litres',
          seat_height: '804 mm',
          rating: '4.6'
        },
        {
          item_id: 'Hero Xtreme',
          desc: "powered by a 199.6 cc air-cooled engine which produces 18.08 PS @ 8500 rpm of power.",
          company: 'Hero',
          model_name: 'Hero Xtreme 200S',
          price: '₹ 1,66,979',
          color: 'Red, White, Black',
          color1: 'White',
          color2: 'Red',
          color3: 'Black',
          itemImg: 'assets/xtreme.jpg',
          itemImg1: 'assets/xtreme.jpg',
          itemImg2: 'assets/xtreme1.jpg',
          itemImg3: 'assets/xtreme2.jpg',
          engine_capacity: '199.6 cc',
          mileage: '40 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '154.5 kg',
          fuel_tank_capacity: '12.8 litres',
          seat_height: '795 mm',
          rating: '4.1'
        },
        {
          item_id: 'Honda CB200X',
          desc: "powered by 184.4cc BS6 engine which develops a power of 17 bhp and a torque of 16.1 Nm.",
          company: 'Honda',
          model_name: 'Honda CB200X',
          price: '₹ 1,78,041',
          color: 'Grey, Red, Black',
          color1: 'Grey',
          color2: 'Red',
          color3: 'Black',
          itemImg: 'assets/cb200x.jpg',
          itemImg1: 'assets/cb200x1.jpg',
          itemImg2: 'assets/cb200x2.jpg',
          itemImg3: 'assets/cb200x3.jpg',
          engine_capacity: '184.4 cc',
          mileage: '43 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '147 kg',
          fuel_tank_capacity: '12 litres',
          seat_height: '810 mm',
          rating: '4'
        },
        {
          item_id: 'Harley-Davidson X440',
          desc: "powered by 440cc BS6 engine which develops a power of 27 bhp and a torque of 38 Nm.",
          company: 'Harley-Davidson',
          model_name: 'Harley-Davidson X440',
          price: '₹ 2,78,581',
          color: 'Black, Red, Green',
          color1: 'Green',
          color2: 'Red',
          color3: 'Black',
          itemImg: 'assets/x440.jpg',
          itemImg1: 'assets/x4401.jpg',
          itemImg2: 'assets/x4402.jpg',
          itemImg3: 'assets/x4403.jpg',
          engine_capacity: '440 cc',
          mileage: '35 kmpl',
          transmission: '6 Speed Manual',
          kerb_weight: '190.5 kg',
          fuel_tank_capacity: '13.5 litres',
          seat_height: '805 mm',
          rating: '4.8'
        },
        {
          item_id: 'TVS Ronin',
          desc: "powered by 225.9cc BS6 engine which develops a power of 20.1 bhp and a torque of 19.93 Nm.",
          company: 'TVS',
          model_name: 'TVS Ronin',
          price: '₹ 1,81,296',
          color: 'Blue, Black, Red',
          color1: 'Blue',
          color2: 'Red',
          color3: 'Black',
          itemImg: 'assets/ronin.jpg',
          itemImg1: 'assets/ronin1.jpg',
          itemImg2: 'assets/ronin2.jpg',
          itemImg3: 'assets/ronin3.jpg',
          engine_capacity: '225.9 cc',
          mileage: '42 kmpl',
          transmission: '5 Speed Manual',
          kerb_weight: '159 kg',
          fuel_tank_capacity: '14 litres',
          seat_height: '795 mm',
          rating: '4.6'
        },
      ]
    },

    {
      id: 2,
      vehicle_name: 'Cars',
      vehicle_id: 'cars',
      vehicleImg: 'assets/car black.png',
      desc1: 'A car or an automobile is a motor vehicle with wheels. Most definitions of cars say that they run primarily on roads, seat one to eight people, have four wheels, and mainly transport people, not cargo',
      desc2: 'Cars have controls for driving, parking, passenger comfort, and a variety of lights. Over the decades, additional features and controls have been added to vehicles, making them progressively more complex. These include rear-reversing cameras, air conditioning, navigation systems, and in-car entertainment. Most cars in use in the early 2020s are propelled by an internal combustion engine, fuelled by the combustion of fossil fuels. Electric cars, which were invented early in the history of the car, became commercially available in the 2000s and are predicted to cost less to buy than gasoline cars before 2025.',
      prod_item: [
        {
          item_id: 'Honda City',
          desc: "powered by the 1,498 cc, 4-cylinder i-VTEC engine that puts out 121 PS of peak power and 145 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda City',
          price: '₹ 11.60 - 16.08 Lakh',
          color: 'Maroon, Blue, Steel',
          color1: 'Maroon',
          color2: 'Blue',
          color3: 'Steel',
          itemImg: 'assets/city.jpg',
          itemImg1: 'assets/city1.jpg',
          itemImg2: 'assets/city2.jpg',
          itemImg3: 'assets/city3.jpg',
          engine_capacity: '1498 cc',
          mileage: '17.8 to 18.4 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1,107 to 1,280 kg',
          fuel_tank_capacity: '40 litres',
          seat_height: '5 Seater',
          rating: '4.2'
        },
        {
          item_id: 'Mahindra Scrrpion',
          desc: "powered by the 2184 cc, Turbo Petrol Direct Injection (TGDi)& mStallion 75 bhp can generate power and 400 Nm torque.",
          company: 'Mahindra',
          model_name: 'Mahindra Scrrpion',
          price: '₹ 13.00 - 16.81 Lakh',
          color: 'Grey, Steel, Red',
          color1: 'Grey',
          color2: 'Steel',
          color3: 'Red',
          itemImg: 'assets/scorpion.jpg',
          itemImg1: 'assets/scorpion1.jpg',
          itemImg2: 'assets/scorpion2.jpg',
          itemImg3: 'assets/scorpion3.jpg',
          engine_capacity: '2184 cc',
          mileage: '15.19 kmpl',
          transmission: 'Manual',
          kerb_weight: '1800 kg',
          fuel_tank_capacity: '60 litres',
          seat_height: '7 & 9 Seater',
          rating: '4.8'
        },
        {
          item_id: 'Maruti Suzuki Brezza',
          desc: "powered by a 1.5-litre petrol engine producing 103hp and 137Nm of torque.",
          company: 'Maruti',
          model_name: 'Maruti Suzuki Brezza',
          price: '₹ 8.29 - 14.14 Lakh',
          color: 'Red, Blue, Steel',
          color1: 'Blue',
          color2: 'Red',
          color3: 'Steel',
          itemImg: 'assets/brezza.jpg',
          itemImg1: 'assets/brezza1.jpg',
          itemImg2: 'assets/brezza2.jpg',
          itemImg3: 'assets/brezza3.jpg',
          engine_capacity: '1462 cc',
          mileage: '17.38 to 25.51 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1180 Kg',
          fuel_tank_capacity: '48 litres',
          seat_height: '5 Seater',
          rating: '4.4'
        },
        {
          item_id: 'Hyundai Verna',
          desc: "powered by the 1482 cc Petrol engine generates a power of 157.57bhp@5500rpm and a torque of 253Nm@1500-3500rpm.",
          company: 'Hyundai',
          model_name: 'Hyundai Verna',
          price: '₹ 10.90 - 17.38 Lakh',
          color: 'Grey, White, Maroon',
          color1: 'Grey',
          color2: 'White',
          color3: 'Maroon',
          itemImg: 'assets/verna.jpg',
          itemImg1: 'assets/verna1.jpg',
          itemImg2: 'assets/verna2.jpg',
          itemImg3: 'assets/verna3.jpg',
          engine_capacity: '1482 to 1497 cc',
          mileage: '18.6 to 20.6 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1277 Kg',
          fuel_tank_capacity: '45 litres',
          seat_height: '5 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Tata Nexon',
          desc: "powered by 3 cylinder, 1199 cc, 1.2L Revotron Turbocharged 120 PS @ 5500 rpm can generate power and 170 Nm @ 1750-4000 rpm torque..",
          company: 'Tata',
          model_name: 'Tata Nexon',
          price: '₹ 7.80 - 8.00 Lakh',
          color: 'Olive, Steel, Blue',
          color1: 'Olive',
          color2: 'Steel',
          color3: 'Blue',
          itemImg: 'assets/nexon.jpg',
          itemImg1: 'assets/nexon1.jpg',
          itemImg2: 'assets/nexon2.jpg',
          itemImg3: 'assets/nexon3.jpg',
          engine_capacity: '1199 to 1497 cc',
          mileage: '17.05 to 24.07 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1320 Kg',
          fuel_tank_capacity: '44 litres',
          seat_height: '5 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Mercedes-Benz',
          desc: "powered by a 1496 cc Petrol engine generates a power of 201.15bhp@5800-6800rpm and a torque of 300Nm@1800-4000rpm.",
          company: 'Mercedes-Benz',
          model_name: 'Mercedes-Benz C-Class',
          price: '₹ 59.99 - 65.99 Lakh',
          color: 'Steel, Blue, Black',
          color1: 'Black',
          color2: 'Steel',
          color3: 'Blue',
          itemImg: 'assets/cclass.jpg',
          itemImg1: 'assets/cclass1.jpg',
          itemImg2: 'assets/cclass2.jpg',
          itemImg3: 'assets/cclass3.jpg',
          engine_capacity: '1496 to 1993 cc',
          mileage: '17 to 23 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1,650 to 1,775 kg',
          fuel_tank_capacity: '40 to 50 litres',
          seat_height: '5 Seater',
          rating: '4.1'
        },
        {
          item_id: 'Mahindra Marazzo',
          desc: "powered by the 1497 cc, Turbo Petrol Direct Injection (TGDi)& mStallion 120.96 bhp can generate power and 300 Nm torque.",
          company: 'Mahindra',
          model_name: 'Mahindra Marazzo',
          price: '₹ 16.41 - 19.16 Lakh',
          color: 'Aqua, Black, White',
          color1: 'Black',
          color2: 'Aqua',
          color3: 'White',
          itemImg: 'assets/marazo.jpg',
          itemImg1: 'assets/marazo.jpg',
          itemImg2: 'assets/marazo1.jpg',
          itemImg3: 'assets/marazo2.jpg',
          engine_capacity: '1497 cc',
          mileage: '17 kmpl',
          transmission: 'Manual',
          kerb_weight: '1,650 kg',
          fuel_tank_capacity: '45 litres',
          seat_height: '7 & 8 Seater',
          rating: '4.3'
        },
        {
          item_id: 'Ford EcoSport',
          desc: "powered by a 3 cylinder, 1496 cc, 1.5 litre petrol Engine 122PS@6500rpm can generate power and 149Nm@4500rpm torque.",
          company: 'Ford',
          model_name: 'Ford EcoSport',
          price: '₹ 7.91 Lakh',
          color: 'White, Blue, Red',
          color1: 'Blue',
          color2: 'Red',
          color3: 'White',
          itemImg: 'assets/ecosport.jpg',
          itemImg1: 'assets/ecosport1.jpg',
          itemImg2: 'assets/ecosport2.jpg',
          itemImg3: 'assets/ecosport3.jpg',
          engine_capacity: '999 to 1498 cc',
          mileage: '14.8 to 22.26 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1188 kg',
          fuel_tank_capacity: '52 litres',
          seat_height: '5 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Volkswagen Virtus',
          desc: "powered by the 1498 cc Petrol engine generates a power of 147.51bhp@5000-6000rpm and a torque of 250Nm@1600-3500rpm.",
          company: 'Volkswagen',
          model_name: 'Volkswagen Virtus',
          price: '₹ 11.48 - 18.76 Lakh',
          color: 'Maroon, Blue, Steel',
          color1: 'Blue',
          color2: 'Maroon',
          color3: 'Steel',
          itemImg: 'assets/virtus.jpg',
          itemImg1: 'assets/virtus1.jpg',
          itemImg2: 'assets/virtus2.jpg',
          itemImg3: 'assets/virtus3.jpg',
          engine_capacity: '999 to 1498 cc',
          mileage: '18.45 to 20.8 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1,173 to 1,269 kg',
          fuel_tank_capacity: '45 litres',
          seat_height: '5 Seater',
          rating: '4.7'
        },
        {
          item_id: 'Hyundai Creta',
          desc: "powered by the 1493 cc Petrol engine generates a power of 113.45bhp@4000rpm and a torque of 250Nm@1500-2750rpm.",
          company: 'Hyundai',
          model_name: 'Hyundai Creta',
          price: '₹ 12.71 - 22.31 Lakh',
          color: 'Black, White, Blue',
          color1: 'Blue',
          color2: 'Black',
          color3: 'White',
          itemImg: 'assets/creta.jpg',
          itemImg1: 'assets/creta.jpg',
          itemImg2: 'assets/creta1.jpg',
          itemImg3: 'assets/creta2.jpg',
          engine_capacity: '1493 to 1497 cc',
          mileage: '18.6 to 20.6 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1,230 to 1,344 kg',
          fuel_tank_capacity: '50 litres',
          seat_height: '5 Seater',
          rating: '4.7'
        },
        {
          item_id: 'BMW X4',
          desc: "powered by a 3.0-liter BMW M TwinPower Turbo inline 6-cylinder engine – yielding 473 horsepower and 442 lb-ft of torque.",
          company: 'BMW',
          model_name: 'BMW X4',
          price: '₹ 62.37 Lakh',
          color: 'Black, Blue, White',
          color1: 'Blue',
          color2: 'Black',
          color3: 'White',
          itemImg: 'assets/x4.jpg',
          itemImg1: 'assets/x41.jpg',
          itemImg2: 'assets/x42.jpg',
          itemImg3: 'assets/x43.jpg',
          engine_capacity: '1197 cc',
          mileage: '20 - 27 kmpl',
          transmission: 'Manual',
          kerb_weight: '935 to 1,050 kg',
          fuel_tank_capacity: '32 to 65 litres',
          seat_height: '5 & 7 Seater',
          rating: '4.8'
        },
        {
          item_id: 'Toyota Innova',
          desc: "powered by 2393 cc Diesel engine generates a power of 147.51bhp@3400rpm and a torque of 343Nm@1400-2800rpm.",
          company: 'Toyota',
          model_name: 'Toyota Innova Crysta',
          price: '₹ 17.18 Lakh',
          color: 'Black, Steel, Grey',
          color1: 'Steel',
          color2: 'Black',
          color3: 'Grey',
          itemImg: 'assets/innova.jpg',
          itemImg1: 'assets/innova1.jpg',
          itemImg2: 'assets/innova2.jpg',
          itemImg3: 'assets/innova3.jpg',
          engine_capacity: '2393 cc',
          mileage: '18.45 to 20.8 kmpl',
          transmission: 'Manual',
          kerb_weight: '1575 kg',
          fuel_tank_capacity: '52 litres',
          seat_height: '7 & 8 Seater',
          rating: '4.8'
        },
        {
          item_id: 'Chevrolet Spark',
          desc: "powered by 995 cc Diesel engine generates a power of 62.1bhp@5400rpm and a torque of 90.3Nm@4200rpm.",
          company: 'Chevrolet',
          model_name: 'Chevrolet Spark',
          price: '₹ 3.73 Lakh',
          color: 'Red, Steel, Black',
          color1: 'Steel',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/spark.jpg',
          itemImg1: 'assets/spark1.jpg',
          itemImg2: 'assets/spark2.jpg',
          itemImg3: 'assets/spark3.jpg',
          engine_capacity: '995 cc',
          mileage: '18 kmpl',
          transmission: 'Manual',
          kerb_weight: '985 kg',
          fuel_tank_capacity: '38 litres',
          seat_height: '5 Seater',
          rating: '3.5'
        },
        {
          item_id: 'Hyundai Venue',
          desc: "powered by the 998 cc Petrol engine generates a power of 118.41bhp@6000rpm and a torque of 172Nm@1500-4000rpm.",
          company: 'Hyundai',
          model_name: 'Hyundai Venue',
          price: '₹ 9.00 - 15.31 Lakh',
          color: 'Black, Red, Blue',
          color1: 'Blue',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/venue.jpg',
          itemImg1: 'assets/venue.jpg',
          itemImg2: 'assets/venue1.jpg',
          itemImg3: 'assets/venue2.jpg',
          engine_capacity: '998 to 1493 cc',
          mileage: '17.5 to 23.4 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1,233 kg',
          fuel_tank_capacity: '45 litres',
          seat_height: '5 Seater',
          rating: '4.6'
        },
        {
          item_id: 'Honda Amaze',
          desc: "powered by Diesel engine is 1199 cc, 4-cylinder i-VTEC engine that puts out 66 PS of peak power and 110 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda Amaze',
          price: '₹ 8.09 - 11.02 Lakh',
          color: 'Maroon, Blue, White',
          color1: 'Maroon',
          color2: 'Blue',
          color3: 'White',
          itemImg: 'assets/amaze.jpg',
          itemImg1: 'assets/city1.jpg',
          itemImg2: 'assets/city2.jpg',
          itemImg3: 'assets/city3.jpg',
          engine_capacity: '1199 cc',
          mileage: '18.3 to 18.6 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '905 to 957 kg',
          fuel_tank_capacity: '35 litres',
          seat_height: '5 Seater',
          rating: '4.3'
        },
        {
          item_id: 'Audi A4',
          desc: "powered by 1984 cc Diesel engine generates a power of 190bhp@4200-6000rpm and a torque of 320Nm@1450–4200rpm.",
          company: 'Audi',
          model_name: 'Audi A4',
          price: '₹ 43.81 - 51.85 Lakh',
          color: 'Black, Blue, Red',
          color1: 'Blue',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/a4.jpg',
          itemImg1: 'assets/a41.jpg',
          itemImg2: 'assets/a42.jpg',
          itemImg3: 'assets/a43.jpg',
          engine_capacity: '1984 cc',
          mileage: '18 kmpl',
          transmission: 'Automatic',
          kerb_weight: '985 kg',
          fuel_tank_capacity: '54 litres',
          seat_height: '5 Seater',
          rating: '4.6'
        },
        {
          item_id: 'Maruti Wagon R',
          desc: "powered by a 1.5-litre petrol engine producing 103hp and 137Nm of torque.",
          company: 'Maruti',
          model_name: 'Maruti Wagon R',
          price: '₹ 6.45 - 8.62 Lakh',
          color: 'Red, Skyblue, Black',
          color1: 'Skyblue',
          color2: 'Black',
          color3: 'Red',
          itemImg: 'assets/wagonr.jpg',
          itemImg1: 'assets/wagonr1.jpg',
          itemImg2: 'assets/wagonr2.jpg',
          itemImg3: 'assets/wagonr3.jpg',
          engine_capacity: '998 to 1197 cc',
          mileage: '23.56 to 34.05 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '810-835 Kg',
          fuel_tank_capacity: '32 litres',
          seat_height: '5 Seater',
          rating: '4.4'
        },
        {
          item_id: 'Renault Duster',
          desc: "2 engine options that are / compliant and 2 transmission options: Manual & Automatic. Other key specifications of the Nexon include a kerb weight of, ground clearance of 209 and boot space of 350 Liters",
          company: 'Renault',
          model_name: 'Renault Duster',
          price: '₹ 8.59 Lakh',
          color: 'Brown, Orenge, Blue',
          color1: 'Brown',
          color2: 'Orenge',
          color3: 'Blue',
          itemImg: 'assets/duster.jpg',
          itemImg1: 'assets/duster1.jpg',
          itemImg2: 'assets/duster2.jpg',
          itemImg3: 'assets/duster3.jpg',
          rating: '4.2'
        },
        {
          item_id: 'Kia Seltos',
          desc: "2 engine options that are / compliant and 2 transmission options: Manual & Automatic. Other key specifications of the Nexon include a kerb weight of, ground clearance of 209 and boot space of 350 Liters",
          company: 'Kia',
          model_name: 'Kia Seltos',
          price: '₹ 10.89 - 19.65 Lakh',
          color: 'Maroon, Blue, Black',
          color1: 'Maroon',
          color2: 'Black',
          color3: 'Blue',
          itemImg: 'assets/seltos.jpg',
          itemImg1: 'assets/seltos1.jpg',
          itemImg2: 'assets/seltos2.jpg',
          itemImg3: 'assets/seltos3.jpg',
          rating: '4.5'
        },
        {
          item_id: 'Bugatti Veyron',
          desc: "2 engine options that are / compliant and 2 transmission options: Manual & Automatic. Other key specifications of the Nexon include a kerb weight of, ground clearance of 209 and boot space of 350 Liters",
          company: 'Bugatti',
          model_name: 'Bugatti Veyron',
          price: '₹ 11.39 Crore',
          color: 'Blue, Yellow, White',
          color1: 'White',
          color2: 'Yellow',
          color3: 'Blue',
          itemImg: 'assets/veyron.jpg',
          itemImg1: 'assets/veyron1.jpg',
          itemImg2: 'assets/veyron2.jpg',
          itemImg3: 'assets/veyron3.jpg',
          engine_capacity: '1197 cc',
          mileage: '20 - 27 kmpl',
          transmission: 'Manual',
          kerb_weight: '935 to 1,050 kg',
          fuel_tank_capacity: '32 to 65 litres',
          seat_height: '5 & 7 Seater',
          rating: '5'
        },
        {
          item_id: 'Land Rover Range Rover',
          desc: "2 engine options that are / compliant and 2 transmission options: Manual & Automatic. Other key specifications of the Nexon include a kerb weight of, ground clearance of 209 and boot space of 350 Liters",
          company: 'Land Rover',
          model_name: 'Land Rover Range Rover',
          price: '₹ 2.39 - 4.17 Crore',
          color: 'Black, Blue, White',
          color1: 'White',
          color2: 'Black',
          color3: 'Blue',
          itemImg: 'assets/rangerover.jpg',
          itemImg1: 'assets/rangerover1.jpg',
          itemImg2: 'assets/rangerover2.jpg',
          itemImg3: 'assets/rangerover3.jpg',
          engine_capacity: '1197 cc',
          mileage: '20 - 27 kmpl',
          transmission: 'Manual',
          kerb_weight: '935 to 1,050 kg',
          fuel_tank_capacity: '32 to 65 litres',
          seat_height: '5 & 7 Seater',
          rating: '4.7'
        },
        {
          item_id: 'Honda Civic',
          desc: "powered by Diesel engine is 1597 cc while the Petrol engine is 1799 cc, 4-cylinder i-VTEC engine that puts out 141 PS of peak power and 174 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda Civic',
          price: '₹ 19.81 Lakh',
          color: 'Maroon, Brown, White',
          color1: 'Maroon',
          color2: 'Brown',
          color3: 'White',
          itemImg: 'assets/civic.jpg',
          itemImg1: 'assets/civic1.jpg',
          itemImg2: 'assets/civic2.jpg',
          itemImg3: 'assets/civic3.jpg',
          engine_capacity: '1597 to 1799 cc',
          mileage: '16.5 to 25.35 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1353 kg',
          fuel_tank_capacity: '47 litres',
          seat_height: '5 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Maruti Swift',
          desc: "powered by a 4 cylinder, 1197 cc, Advanced K series Dual Jet& Dual VVT Engine 83.73 bhp @ 6000 rpm can generate power and 113 Nm @ 4400 rpm torque.",
          company: 'Maruti',
          model_name: 'Maruti Swift',
          price: '₹ 6.99 - 10.40 Lakh',
          color: 'Red, Blue, Orenge',
          color1: 'Red',
          color2: 'Orenge',
          color3: 'Blue',
          itemImg: 'assets/swift.jpg',
          itemImg1: 'assets/swift1.jpg',
          itemImg2: 'assets/swift2.jpg',
          itemImg3: 'assets/swift3.jpg',
          engine_capacity: '1197 cc',
          mileage: '22.38 to 30.9 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '980 to 985 kg',
          fuel_tank_capacity: '37 to 55 litres',
          seat_height: '5 Seater',
          rating: '4.4'
        },
        {
          item_id: 'Skoda Rapid',
          desc: "powered by 3 cylinder, 1598 cc, 1.0L TSI Petrol,999 cc& 3 Cylinders Inline& 4 Valves/Cylinder& DOHC 110 PS @ 5000rpm can generate power and 175 Nm @ 1750rpm torque.",
          company: 'Skoda',
          model_name: 'Skoda Rapid',
          price: '₹ 6.99 Lakh',
          color: 'Grey, Blue, Red',
          color1: 'Red',
          color2: 'Grey',
          color3: 'Blue',
          itemImg: 'assets/rapid.jpg',
          itemImg1: 'assets/rapid1.jpg',
          itemImg2: 'assets/rapid2.jpg',
          itemImg3: 'assets/rapid3.jpg',
          engine_capacity: '1498 to 1598 cc',
          mileage: '14.84 to 21.72 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1111 kg',
          fuel_tank_capacity: '55 litres',
          seat_height: '5 Seater',
          rating: '4.3'
        },
        {
          item_id: 'Nissan Micra Active',
          desc: "powered by 1198 cc, 3 Cylinders Inline, 4 Valves/Cylinder, DOHC ; Engine Type. 3 cylinder petrol engine ; Fuel Type. Petrol ; Max Power (bhp@rpm). 67 bhp @ 5000 rpm.",
          company: 'Nissan',
          model_name: 'Nissan Micra Active',
          price: '₹ 5.25 Lakh',
          color: 'Maroon, Blue, Black',
          color1: 'Maroon',
          color2: 'Black',
          color3: 'Blue',
          itemImg: 'assets/micra.jpg',
          itemImg1: 'assets/micra1.jpg',
          itemImg2: 'assets/micra2.jpg',
          itemImg3: 'assets/micra3.jpg',
          engine_capacity: '1198 cc',
          mileage: '19.21 kmpl',
          transmission: 'Manual',
          kerb_weight: '950 kg',
          fuel_tank_capacity: '41 litres',
          seat_height: '5 Seater',
          rating: '3.9'
        },
        {
          item_id: 'Maruti Eeco',
          desc: "powered by a 1.5-litre petrol engine producing 103hp and 137Nm of torque.",
          company: 'Maruti',
          model_name: 'Maruti Eeco',
          price: '₹ 6.21 - 7.61 Lakh',
          color: 'White, Skyblue, Black',
          color1: 'White',
          color2: 'Black',
          color3: 'Skyblue',
          itemImg: 'assets/ecco.jpg',
          itemImg1: 'assets/ecco1.jpg',
          itemImg2: 'assets/ecco2.jpg',
          itemImg3: 'assets/ecco3.jpg',
          engine_capacity: '1197 cc',
          mileage: '20 - 27 kmpl',
          transmission: 'Manual',
          kerb_weight: '935 to 1,050 kg',
          fuel_tank_capacity: '32 to 65 litres',
          seat_height: '5 & 7 Seater',
          rating: '4.6'
        },
        {
          item_id: 'Jaguar XJ L 3.0',
          desc: "2 engine options that are / compliant and 2 transmission options: Manual & Automatic. Other key specifications of the Nexon include a kerb weight of, ground clearance of 209 and boot space of 350 Liters",
          company: 'Jaguar',
          model_name: 'Jaguar XJ L 3.0',
          price: '₹ 1.10 Crore',
          color: 'Black, White, Maroon',
          color1: 'White',
          color2: 'Black',
          color3: 'Maroon',
          itemImg: 'assets/xjl.jpg',
          itemImg1: 'assets/xjl1.jpg',
          itemImg2: 'assets/xjl2.jpg',
          itemImg3: 'assets/xjl3.jpg',
          engine_capacity: '1197 cc',
          mileage: '20 - 27 kmpl',
          transmission: 'Manual',
          kerb_weight: '935 to 1,050 kg',
          fuel_tank_capacity: '32 to 65 litres',
          seat_height: '5 & 7 Seater',
          rating: '4.9'
        },
        {
          item_id: 'Honda Jazz',
          desc: "powered by Diesel engine is 1199 cc while the Petrol engine is 1799 cc, 4-cylinder i-VTEC engine that puts out 110 PS of peak power and 110 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda Jazz',
          price: '₹ 8.90 Lakh',
          color: 'Red, Steel, Grey',
          color1: 'Red',
          color2: 'Steel',
          color3: 'Grey',
          itemImg: 'assets/jazz.jpg',
          itemImg1: 'assets/jazz1.jpg',
          itemImg2: 'assets/jazz2.jpg',
          itemImg3: 'assets/jazz3.jpg',
          engine_capacity: '1199 cc',
          mileage: '16.6 to 17.1 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1042 kg',
          fuel_tank_capacity: '40 litres',
          seat_height: '5 Seater',
          rating: '4.4'
        },
        {
          item_id: 'Maruti Dzire',
          desc: "powered by a 1.5-litre petrol engine producing 103hp and 137Nm of torque.",
          company: 'Maruti',
          model_name: 'Maruti Dzire',
          price: '₹ 7.59 - 10.83 Lakh',
          color: 'Maroon, Blue, White',
          color1: 'Maroon',
          color2: 'Blue',
          color3: 'White',
          itemImg: 'assets/dzire.jpg',
          itemImg1: 'assets/dzire.jpg',
          itemImg2: 'assets/dzire1.jpg',
          itemImg3: 'assets/dzire2.jpg',
          engine_capacity: '1197 cc',
          mileage: '22.41 to 31.12 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '880 to 990 kg',
          fuel_tank_capacity: '37 to 55 litres',
          seat_height: '5 Seater',
          rating: '4.6'
        },
        {
          item_id: 'Hyundai i20',
          desc: "powered by the 998 cc Petrol engine generates a power of 118.41bhp@6000rpm and a torque of 172Nm@1500-4000rpm.",
          company: 'Hyundai',
          model_name: 'Hyundai i20 N Line',
          price: '₹ 11.86 - 14.31 Lakh',
          color: 'Blue, Red, Steel',
          color1: 'Red',
          color2: 'Blue',
          color3: 'Steel',
          itemImg: 'assets/i20.jpg',
          itemImg1: 'assets/i20.jpg',
          itemImg2: 'assets/i201.jpg',
          itemImg3: 'assets/i202.jpg',
          engine_capacity: '998 cc',
          mileage: '20.2 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1210 Kg',
          fuel_tank_capacity: '37 litres',
          seat_height: '5 Seater',
          rating: '4.1'
        },
        {
          item_id: 'Mahindra Thar',
          desc: "powered by the 1497 to 2184 cc, Turbo Petrol Direct Injection (TGDi)& mStallion 130 bhp can generate power and 300 Nm torque.",
          company: 'Mahindra',
          model_name: 'Mahindra Thar',
          price: '₹ 11.62 - 18.84 Lakh',
          color: 'White, Black, Red',
          color1: 'Red',
          color2: 'Black',
          color3: 'White',
          itemImg: 'assets/thar.jpg',
          itemImg1: 'assets/thar.jpg',
          itemImg2: 'assets/thar1.jpg',
          itemImg3: 'assets/thar2.jpg',
          engine_capacity: '1497 to 2184 cc',
          mileage: '16.3 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1710 kg',
          fuel_tank_capacity: '45 to 57 litres',
          seat_height: '4 Seater',
          rating: '4.7'
        },
        {
          item_id: 'Lamborghini Huracan Evo',
          desc: "2 engine options that are / compliant and 2 transmission options: Manual & Automatic. Other key specifications of the Nexon include a kerb weight of, ground clearance of 209 and boot space of 350 Liters",
          company: 'Lamborghini',
          model_name: 'Lamborghini Huracan Evo',
          price: '₹ 3.22 - 3.73 Crore',
          color: 'Orange, Red, Black',
          color1: 'Red',
          color2: 'Black',
          color3: 'Orange',
          itemImg: 'assets/huracanevo.jpg',
          itemImg1: 'assets/huracanevo1.jpg',
          itemImg2: 'assets/huracanevo2.jpg',
          itemImg3: 'assets/huracanevo3.jpg',
          engine_capacity: '1197 cc',
          mileage: '20 - 27 kmpl',
          transmission: 'Manual',
          kerb_weight: '935 to 1,050 kg',
          fuel_tank_capacity: '32 to 65 litres',
          seat_height: '5 & 7 Seater',
          rating: '4.8'
        },
        {
          item_id: 'Maruti Baleno',
          desc: "powered by a 1.5-litre petrol engine producing 103hp and 137Nm of torque.",
          company: 'Maruti',
          model_name: 'Maruti Baleno',
          price: '₹ 7.65 - 11.33 Lakh',
          color: 'Red, Blue, Black',
          color1: 'Red',
          color2: 'Black',
          color3: 'Blue',
          itemImg: 'assets/baleno.jpg',
          itemImg1: 'assets/baleno.jpg',
          itemImg2: 'assets/baleno1.jpg',
          itemImg3: 'assets/baleno2.jpg',
          engine_capacity: '1197 cc',
          mileage: '22.35 to 30.61 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '925 to 1,035 kg',
          fuel_tank_capacity: '37 to 55 litres',
          seat_height: '5 Seater',
          rating: '4.4'
        },
        {
          item_id: 'Hyundai Aura',
          desc: "powered by the 1197 cc Petrol engine generates a power of 81.80bhp@6000rpm and a torque of 113.8Nm@4000rpm.",
          company: 'Hyundai',
          model_name: 'Hyundai Aura',
          price: '₹ 7.41 - 10.35 Lakh',
          color: 'Blue, Red, Steel',
          color1: 'Red',
          color2: 'Steel',
          color3: 'Blue',
          itemImg: 'assets/aura.jpg',
          itemImg1: 'assets/aura.jpg',
          itemImg2: 'assets/aura1.jpg',
          itemImg3: 'assets/aura2.jpg',
          engine_capacity: '1197 cc',
          mileage: '20-28 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '940 kg',
          fuel_tank_capacity: '37 litres',
          seat_height: '5 Seater',
          rating: '4.7'
        },
        {
          item_id: 'Honda Elevate',
          desc: "powered by Diesel engine is 1498 cc, 4-cylinder i-VTEC engine that puts out 121 PS of peak power and 145 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda Elevate',
          price: '₹ 10.00 - 17.00 Lakh',
          color: 'Maroon, Steel, Blue',
          color1: 'Maroon',
          color2: 'Steel',
          color3: 'Blue',
          itemImg: 'assets/elevate.jpg',
          itemImg1: 'assets/elevate1.jpg',
          itemImg2: 'assets/elevate2.jpg',
          itemImg3: 'assets/elevate3.jpg',
          engine_capacity: '1498 cc',
          mileage: '15.31 - 16.92 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1206 - 1258 kg',
          fuel_tank_capacity: '40 litres',
          seat_height: '5 Seater',
          rating: '5'
        },
        {
          item_id: 'Mahindra XUV700',
          desc: "powered by the 1997 to 2184 cc, Turbo Petrol Direct Injection (TGDi)& mStallion 182.38 bhp can generate power and 450 Nm torque.",
          company: 'Mahindra',
          model_name: 'Mahindra XUV700',
          price: '₹ 15.79 - 29.23 Lakh',
          color: 'Red, Blue, Steel',
          color1: 'Red',
          color2: 'Steel',
          color3: 'Blue',
          itemImg: 'assets/xuv700.jpg',
          itemImg1: 'assets/xuv7001.jpg',
          itemImg2: 'assets/xuv7002.jpg',
          itemImg3: 'assets/xuv7003.jpg',
          engine_capacity: '1997 to 2184 cc',
          mileage: '13 - 14.5 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1960 - 2040 kg',
          fuel_tank_capacity: '60 litres',
          seat_height: '5 & 7 Seater',
          rating: '4.6'
        },
        {
          item_id: 'Hyundai Grand i10',
          desc: "powered by the 1197 cc Petrol engine generates a power of 81.80bhp@6000rpm and a torque of 113.8Nm@4000rpm.",
          company: 'Hyundai',
          model_name: 'Hyundai Grand i10 Nios',
          price: '₹ 6.73 - 9.92 Lakh',
          color: 'Black, Red, White',
          color1: 'Red',
          color2: 'White',
          color3: 'Black',
          itemImg: 'assets/i10.jpg',
          itemImg1: 'assets/i10.jpg',
          itemImg2: 'assets/i101.jpg',
          itemImg3: 'assets/i102.jpg',
          engine_capacity: '1197 cc',
          mileage: '17.5 to 23.4 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '805 kg',
          fuel_tank_capacity: '37 to 60 litres',
          seat_height: '5 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Honda Accord',
          desc: "powered by Diesel engine is 1993 cc, 4-cylinder i-VTEC engine that puts out 192 PS of peak power and 222 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda Accord',
          price: '₹ 48.46 Lakh',
          color: 'Grey, Steel, Black',
          color1: 'Grey',
          color2: 'Steel',
          color3: 'Black',
          itemImg: 'assets/accord.jpg',
          itemImg1: 'assets/accord1.jpg',
          itemImg2: 'assets/accord2.jpg',
          itemImg3: 'assets/accord3.jpg',
          engine_capacity: '1993 cc',
          mileage: '10.7 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1620 kg',
          fuel_tank_capacity: '60 litres',
          seat_height: '5 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Mahindra Bolero',
          desc: "powered by the 1493 cc, Turbo Petrol Direct Injection (TGDi)& mStallion 74.96 bhp can generate power and 210 Nm torque.",
          company: 'Mahindra',
          model_name: 'Mahindra Bolero',
          price: '₹ 10.69 - 11.89 Lakh',
          color: 'White, Grey, Steel',
          color1: 'Grey',
          color2: 'Steel',
          color3: 'White',
          itemImg: 'assets/bolero.jpg',
          itemImg1: 'assets/bolero1.jpg',
          itemImg2: 'assets/bolero2.jpg',
          itemImg3: 'assets/bolero3.jpg',
          engine_capacity: '1493 cc',
          mileage: '17 kmpl',
          transmission: 'Manual',
          kerb_weight: '1,620 kg',
          fuel_tank_capacity: '60 litres',
          seat_height: '7 Seater',
          rating: '4.5'
        },
        {
          item_id: 'Honda CR-V',
          desc: "powered by Diesel engine is 1993 cc, 4-cylinder i-VTEC engine that puts out 192 PS of peak power and 222 Nm of torque.",
          company: 'Honda',
          model_name: 'Honda CR-V',
          price: '₹ 31.03 Lakh',
          color: 'Grey, Steel, Maroon',
          color1: 'Grey',
          color2: 'Steel',
          color3: 'Maroon',
          itemImg: 'assets/crv.jpg',
          itemImg1: 'assets/crv1.jpg',
          itemImg2: 'assets/crv2.jpg',
          itemImg3: 'assets/crv3.jpg',
          engine_capacity: '1597 to 1997 cc',
          mileage: '12.0 to 19.5 kmpl',
          transmission: 'Manual & Automatic',
          kerb_weight: '1545 kg',
          fuel_tank_capacity: '58 litres',
          seat_height: '5 Seater',
          rating: '4.4'
        },
      ]
    }
  ]

  bikes: any = [
    { img: 'assets/aprilia.jpg', alt: 'aprilia' },
    { img: 'assets/bmw.jpg', alt: 'bmw' },
    { img: 'assets/ducati.jpg', alt: 'ducati' },
    { img: 'assets/harley-devidson.jpg', alt: 'harley-devidson' },
    { img: 'assets/suzuki.jpg', alt: 'suzuki' },
    { img: 'assets/benelli.jpg', alt: 'benelli' },
    { img: 'assets/norton.jpg', alt: 'norton' },
    { img: 'assets/yamaha.jpg', alt: 'yamaha' },
    { img: 'assets/honda.jpg', alt: 'honda' },
    { img: 'assets/kawasaki.jpg', alt: 'kawasaki' },
    { img: 'assets/ktm.jpg', alt: 'ktm' },
    { img: 'assets/royal-enfield.jpg', alt: 'royal-enfield' },
    { img: 'assets/triumph.jpg', alt: 'triumph' },
    { img: 'assets/moto-guzzi.jpg', alt: 'moto-guzzi' },
    { img: 'assets/bajaj.jpg', alt: 'bajaj' },
    { img: 'assets/tvs.jpg', alt: 'tvs' },
    { img: 'assets/tork.jpg', alt: 'tork' },
    { img: 'assets/revolt.jpg', alt: 'revolt' },
    { img: 'assets/mahindra.jpg', alt: 'mahindra' },
    { img: 'assets/hero.jpg', alt: 'hero' },
  ]
  cars: any = [
    { img: 'assets/maruti-suzuki.jpg', alt: 'maruti-suzuki' },
    { img: 'assets/hyundai.jpg', alt: 'hyundai' },
    { img: 'assets/tata.jpg', alt: 'tata' },
    { img: 'assets/mahindracar.jpg', alt: 'mahindracar' },
    { img: 'assets/bmwcar.jpg', alt: 'bmwcar' },
    { img: 'assets/toyota.jpg', alt: 'toyota' },
    { img: 'assets/mercedes-benz.jpg', alt: 'mercedes-benz' },
    { img: 'assets/kia.jpg', alt: 'kia' },
    { img: 'assets/audi.jpg', alt: 'audi' },
    { img: 'assets/land-rover.jpg', alt: 'land-rover' },
    { img: 'assets/hondacar.jpg', alt: 'hondacar' },
    { img: 'assets/skoda.jpg', alt: 'skoda' },
    { img: 'assets/jaguar.jpg', alt: 'jaguar' },
    { img: 'assets/volkswagen.jpg', alt: 'volkswagen' },
    { img: 'assets/nissan.jpg', alt: 'nissan' },
    { img: 'assets/lamborghini.jpg', alt: 'lamborghini' },
    { img: 'assets/bugatti.jpg', alt: 'bugatti' },
    { img: 'assets/renault.jpg', alt: 'renault' },
    { img: 'assets/ford.jpg', alt: 'ford' },
    { img: 'assets/chevrolet.jpg', alt: 'chevrolet' },
  ]

  latest_bikes: any = [
    {
      model_name: 'Harley-Davidson Custom',
      itemImg: 'assets/harley-devidson(latest).jpg',
      price: '₹ 16,00,000 - ₹ 17,00,000'
    },
    {
      model_name: 'TVS Apache RTR 160',
      itemImg: 'assets/tvs(latest).jpg',
      price: '₹ 1,47,280'
    },
    {
      model_name: 'Benelli 502C',
      itemImg: 'assets/benelli(latest).jpg',
      price: '₹ 7,24,215'
    },
    {
      model_name: 'Honda CB300R',
      itemImg: 'assets/honda(latest).jpg',
      price: '₹ 3,26,290'
    },
    {
      model_name: 'Hero XF3R',
      itemImg: 'assets/hero(latest).jpg',
      price: '₹ 1,60,000 - ₹ 1,80,000'
    },
    {
      model_name: 'Kawasaki Versys X-300',
      itemImg: 'assets/kawasaki(latest).jpg',
      price: '₹ 4,80,000 - ₹ 5,20,000'
    },
  ]

  latest_cars: any = [
    {
      model_name: 'Hyundai Exter',
      itemImg: 'assets/exter.jpg',
      price: '₹ 6.00 - 10.10 Lakh'
    },
    {
      model_name: 'Maruti Invicto',
      itemImg: 'assets/invicto.jpg',
      price: '₹ 24.79 - 28.42 Lakh'
    },
    {
      model_name: 'Maruti Fronx',
      itemImg: 'assets/fronx.jpg',
      price: '₹ 7.47 - 13.14 Lakh'
    },
    {
      model_name: 'Renault Kwid',
      itemImg: 'assets/kwid.jpg',
      price: '₹ 4.70 - 6.45 Lakh'
    },
    {
      model_name: 'Tata Harrier',
      itemImg: 'assets/harrier.jpg',
      price: '₹ 15.20 - 24.27 Lakh'
    },
    {
      model_name: 'Hyundai Aura',
      itemImg: 'assets/auro.jpg',
      price: '₹ 6.33 - 8.90 Lakh'
    },
  ]

  constructor() { }
}
